# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator_right
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - front_rocker
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
    - left_kinova_arm_joint_1
    - left_kinova_arm_joint_2
    - left_kinova_arm_joint_3
    - left_kinova_arm_joint_4
    - left_kinova_arm_joint_5
    - left_kinova_arm_joint_6
    - left_kinova_arm_joint_7
    - left_kinova_arm_gripper_base_joint
    - left_kinova_arm_finger_joint
    - left_kinova_arm_left_outer_finger_joint
    - left_kinova_arm_left_inner_finger_joint
    - left_kinova_arm_left_inner_finger_pad_joint
    - left_kinova_arm_left_inner_knuckle_joint
    - left_kinova_arm_right_inner_knuckle_joint
    - left_kinova_arm_right_outer_knuckle_joint
    - left_kinova_arm_right_outer_finger_joint
    - left_kinova_arm_right_inner_finger_joint
    - left_kinova_arm_right_inner_finger_pad_joint
    - right_kinova_arm_joint_1
    - right_kinova_arm_joint_2
    - right_kinova_arm_joint_3
    - right_kinova_arm_joint_4
    - right_kinova_arm_joint_5
    - right_kinova_arm_joint_6
    - right_kinova_arm_joint_7
    - right_kinova_arm_gripper_base_joint
    - right_kinova_arm_finger_joint
    - right_kinova_arm_left_outer_finger_joint
    - right_kinova_arm_left_inner_finger_joint
    - right_kinova_arm_left_inner_finger_pad_joint
    - right_kinova_arm_left_inner_knuckle_joint
    - right_kinova_arm_right_inner_knuckle_joint
    - right_kinova_arm_right_outer_knuckle_joint
    - right_kinova_arm_right_outer_finger_joint
    - right_kinova_arm_right_inner_finger_joint
    - right_kinova_arm_right_inner_finger_pad_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /left_kinova_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_kinova_arm_joint_1
      - left_kinova_arm_joint_2
      - left_kinova_arm_joint_3
      - left_kinova_arm_joint_4
      - left_kinova_arm_joint_5
      - left_kinova_arm_joint_6
      - left_kinova_arm_joint_7

  - name: /left_kinova_arm_robotiq_2f_85_gripper_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - left_kinova_arm_finger_joint

  - name: /right_kinova_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_kinova_arm_joint_1
      - right_kinova_arm_joint_2
      - right_kinova_arm_joint_3
      - right_kinova_arm_joint_4
      - right_kinova_arm_joint_5
      - right_kinova_arm_joint_6
      - right_kinova_arm_joint_7

  - name: /right_kinova_arm_robotiq_2f_85_gripper_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - right_kinova_arm_finger_joint

  - name: /ewellix_tlt/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - ewellix_lift_top_joint

