controller_list:
  - name: left_kinova_arm/left_kinova_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_kinova_arm_joint_1
      - left_kinova_arm_joint_2
      - left_kinova_arm_joint_3
      - left_kinova_arm_joint_4
      - left_kinova_arm_joint_5
      - left_kinova_arm_joint_6
      - left_kinova_arm_joint_7
  - name: right_kinova_arm/right_kinova_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_kinova_arm_joint_1
      - right_kinova_arm_joint_2
      - right_kinova_arm_joint_3
      - right_kinova_arm_joint_4
      - right_kinova_arm_joint_5
      - right_kinova_arm_joint_6
      - right_kinova_arm_joint_7
  - name: /ewellix_tlt_node/test_server
    action_ns: single_joint_position
    default: True
    type: SingleJointPosition
    joints:
      - ewellix_lift_top_joint
  - name: gripper_left_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - left_kinova_arm_finger_joint
  - name: gripper_right_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - right_kinova_arm_finger_joint
