controller_list:
  - name: left_kinova_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_kinova_arm_joint_1
      - left_kinova_arm_joint_2
      - left_kinova_arm_joint_3
      - left_kinova_arm_joint_4
      - left_kinova_arm_joint_5
      - left_kinova_arm_joint_6
      - left_kinova_arm_joint_7
  - name: right_kinova_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_kinova_arm_joint_1
      - right_kinova_arm_joint_2
      - right_kinova_arm_joint_3
      - right_kinova_arm_joint_4
      - right_kinova_arm_joint_5
      - right_kinova_arm_joint_6
      - right_kinova_arm_joint_7

